### ISSUE TITLE
Breaking pyrite ore with unenchanted pickaxe drops multiple pyrite ore.

### ISSUE THREAD

**Issue by jriwanek** [RacerDelux/MagicalPotionsAndBrews#1]
dupe bug.

**Comment by RacerDelux** [comment]
Has already been fixed in 0.1.3, If you are still having the issue, you must be using an older version.
https://github.com/RacerDelux/MagicalPotionsAndBrews/blob/master/src/main/java/com/squaresuits/magicalpotionsandbrews/blocks/BlockOres.java Line 53 shows only one item from any ore added in this mod can be dropped.
